version: "3.6"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-server-80-hiredhelpr
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=hiredhelpr_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=admin
    ports:
      - "8082:3306"

  api:
    container_name: hiredhelpr-api
    image: api:latest
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/usr/src/app
    ports:
      - 8000:8000
    tty: true
    depends_on:
      - mysql

  app:
    container_name: hiredhelpr-app
    image: app:latest
    build:
      context: ./api/frontend
      dockerfile: Dockerfile
    volumes:
      - ./api/frontend:/var/www/html
    ports:
      - 8080:8080
    tty: true
