# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      # ... steps for building/testing app ...

      - setup_remote_docker:
          docker_layer_caching: true

      # build and push Docker image
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t jfarillas/hiredhelpr-api:$TAG ./api
          docker build -t jfarillas/hiredhelpr-app:$TAG ./api/frontend
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push jfarillas/hiredhelpr-api:$TAG
          docker push jfarillas/hiredhelpr-app:$TAG